version = 1

test_patterns = [
  "tests/**",
  "src/test/**"
]

exclude_patterns = [
  "lib/**",
  "orbit_bundle.js",
  "public/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
